"""update

Revision ID: 5f9afa8d2efe
Revises: 
Create Date: 2026-02-20 16:50:48.420384

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9afa8d2efe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'PLN', 'GBP', 'CZK', name='currency'), nullable=False),
    sa.Column('outstanding_amount', sa.Integer(), nullable=False),
    sa.Column('settlement_currency', sa.Enum('USD', 'EUR', 'PLN', 'GBP', 'CZK', name='currency'), nullable=False),
    sa.Column('capture_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enforce_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authorisation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customers_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_code', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'PLN', 'GBP', 'CZK', name='currency'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('product_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Enum('en', 'ru', 'pl', name='languages'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'lang')
    )
    op.create_table('product_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('file_link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'lang')
    )
    op.create_table('product_card_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_card_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_card_id'], ['product_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_card_images')
    op.drop_table('product_files')
    op.drop_table('product_card')
    op.drop_table('products')
    op.drop_table('orders')
    # ### end Alembic commands ###
